import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageHero from "@/components/PageHero";
import Link from "next/link";
import { ArrowUpRight, Building2, MapPinned, Phone, Store, Warehouse } from "lucide-react";

const spaces = [
  { icon: Store, title: "Shops & showrooms", text: "Retail spaces with visibility, access and a clear front door.", image: "/images/commercial-margao.jpg", shape: "shape-tall" },
  { icon: Building2, title: "Offices", text: "Professional settings for growing teams and enduring businesses.", image: "/images/apt-panjim-2.jpg", shape: "shape-arch" },
  { icon: Warehouse, title: "Warehouses", text: "Storage and logistics spaces with operational potential.", image: "/images/plot-ponda.jpg", shape: "shape-slant" },
];

export default function CommercialPage() {
  return <main className="interior-page min-h-screen bg-pearl"><Navbar /><PageHero eyebrow="Business spaces, selected well" title={<>Commercial<br /><i className="text-champagne">property in Goa.</i></>} description="Workspaces, retail settings and land opportunities evaluated through an operational lens." image="/images/commercial-margao.jpg" number="10" /><section className="section-spacing"><div className="mx-auto max-w-[1440px] px-5 md:px-8"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end" data-reveal><div><p className="font-[Manrope] text-[10px] tracking-[.28em] text-champagne uppercase">The commercial edit</p><h2 className="mt-3 font-[Cormorant_Garamond] text-5xl font-light leading-[.85] text-sand">Space that gives<br />business <i>room to move.</i></h2></div><Link href="/properties?category=commercial" className="luxury-button">View commercial listings <ArrowUpRight size={15} /></Link></div><div className="grid gap-5 md:grid-cols-3">{spaces.map((space, index) => <article key={space.title} data-reveal data-reveal-delay={String(index * .1)} className={`group relative min-h-[380px] overflow-hidden border border-white/10 ${space.shape}`}><img src={space.image} alt="" className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-obsidian via-obsidian/15 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6"><space.icon size={19} className="text-champagne" /><h3 className="mt-4 font-[Cormorant_Garamond] text-3xl font-light text-sand">{space.title}</h3><p className="mt-2 font-[Manrope] text-xs leading-5 text-sand/60">{space.text}</p></div></article>)}</div></div></section><section className="border-y border-champagne/15 bg-obsidian"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-12 md:grid-cols-[.7fr_1.3fr] md:px-8 md:py-16"><div><MapPinned size={27} className="text-champagne" /><p className="mt-4 font-[Manrope] text-[10px] tracking-[.2em] text-sand/45 uppercase">An advisor-led search</p></div><div><p className="font-[Cormorant_Garamond] text-3xl font-light leading-tight text-sand md:text-4xl">The right commercial property starts with how it needs to work — not only how it looks.</p><a href="tel:+918208337147" className="mt-6 inline-flex items-center gap-2 font-[Manrope] text-[10px] tracking-[.16em] text-champagne uppercase">Speak with a commercial advisor <Phone size={14} /></a></div></div></section><Footer /></main>;
}
